language: java
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker

script: 
  - docker build . -t scorpio13/status-ms:latest
  - docker image ls
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push scorpio13/status-ms:latest